### PR TITLE
Create 00700-kendraio.md

### PR DESCRIPTION
**Pull request by dahacouk**
Created workshop idea for Kendra Hub (Open Value Network for Music Makers). @dahacouk is happy to receive comments and/or questions.

### CODE REVIEW

**Comment by pierreozoux** [comment]
Thanks a lot for your PR!

And sorry for the delay :/

Can you tell us more about:
- how you envision collaboration with other present project
- which project already present you are interested to collaborate with

And as I don't want to take the decision (and I don't want to have this power) to merge it or not, I let the crowd take this decision :) After 2 :+1: I merge :) What do you think?

Best!

Pierre

**Comment by dahacouk** [comment]
Yes, I saw there was a lack of pull requests so I thought I'd help out! ;-)
- [Kendra Hub](https://www.kendra.io/kendra-hub) is an open source application being developed by [Kendra Initiative](https://www.kendra.io) to be used by creatives and copyright owners to manage their media assets and credit/copyright assertions. The application will need to integrate with cloud storage service providers and obviously we'd like to provide as much freedom of choice as possible. We are also heavily using semantic objects for portability and interoperability.
- So, collaboration will surely be with cloud service providers present. But there are a number of other people/organisations present that we'd like to work with such as Henry Story for semantics.

My intention behind creating a workshop/discussion cluster around Kendra Hub is to demonstrate how distributed and semantic architectures could be used by established "old world" industries to enable greater freedom of choice whilst encouraging current media industry service providers to be more open. The project is a real world use case for these technologies.

I'm happy to go with your "decision" methodology! ;-)
- [x] With regards to listing the Kendra Hub project itself and with listing myself should I just similarly make pull requests for those too?

Cheers Daniel

**Comment by pierreozoux** [comment]
Thanks for your description :)

I :+1: myself :)

About Kendra HUB project and yourself, I'll ask you to PR once this one is merged.

**Comment by dahacouk** [comment]
Coolio. I'll get the data ready so that I can just push a button once we have another :+1: from the @ouishare @ouisharelabs teams. Cheers!

**Comment by elf-pavlik** [comment]
:+1: @dahacouk can you please share link to video with your presentation about it? the one which you start by arguing with session host about t-shirt :smiling_imp:

**Comment by dahacouk** [comment]
Sure @elf-pavlik it's https://youtu.be/VLUoBGMA0Ac

Enjoy! :smile:

**Pull request merged**
